name: release

on:
  release:
    types: [created] # 标识在创建新的 Release 时触发

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows] # 需要打包的系统
        goarch: [amd64, arm64] # 需要打包的架构
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.30
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # 一个默认的变量，用来实现往 Release 中添加文件
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.22.1 # 可以指定编译使用的 Golang 版本
          extra_files: LICENSE README.md # 需要包含的额外文件